# Generated by Django 2.2.1 on 2019-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='seguitores_nombres',
            field=models.TextField(default=''),
        ),
    ]
