# Generated by Django 2.2.1 on 2019-06-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='Personas_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.TextField(default='[]'),
        ),
    ]
